version: 0.2
phases:
  pre_build:
    commands:
    - echo "Logging in to Amazon PROD ECR...."
  build:
    commands:
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - COMMIT_SHA=$(git rev-parse --short HEAD)
    - BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed "s/\\//-/g" | tr '[:upper:]' '[:lower:]')
    - TIMESTAMP="$(date +%s)"
    - IMAGE_TAG=${BRANCH_NAME}-${COMMIT_SHA}-${TIMESTAMP}
  post_build:
    commands:
    - echo Build completed on `date`
    - export BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d / -f 2)
    - echo $BRANCH_NAME
    - bash -c '
        echo "This is a Bash script"
        echo "The current directory is $PWD"
        echo "The current date is $(date)"
        if [[ $BRANCH_NAME =~ ^Release.* ]]; then
            echo "This is a Release Branch"
        else
            echo "This is a NON Release Branch"
        fi'
