version: 0.2
phases:
  pre_build:
    commands:
    - echo "Logging in to Amazon PROD ECR...."
  build:
    commands:
    - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
    - COMMIT_SHA=$(git rev-parse --short HEAD)
    - BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | sed "s/\\//-/g" | tr '[:upper:]' '[:lower:]')
    - TIMESTAMP="$(date +%s)"
    - IMAGE_TAG=${BRANCH_NAME}-${COMMIT_SHA}-${TIMESTAMP}
  post_build:
    commands:
    - echo Build completed on `date`
    - export BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d / -f 2)
    - |
      #!/bin/bash
      bash --version
      BRANCH_NAME='Release-1'
      RELEASE_STRING='Release*'
      if [ "$VAR" = "value" ] || [ "$VAR" = "other" ]; then
        echo "Value is either 'value' or 'other'"
      fi
