build:
  commands:
    - echo "The value of CODEBUILD_SOURCE_VERSION is: $CODEBUILD_SOURCE_VERSION"
    - export BRANCH_NAME=$(echo $CODEBUILD_SOURCE_VERSION | cut -d / -f 2)
    - |
      #!/bin/bash
      if [ "$BRANCH_NAME" = "master" ]; then
        echo "This is the master branch"
      else
        echo "This is NOT the master branch"
      fi
