---
version: 1
metadata:
  pipelineName: my-pipeline
stages:
  - name: Source
    actions:
      - name: SourceAction
        actionTypeId:
          category: Source
          owner: AWS
          provider: CodeCommit
          version: '1'
        configuration:
          RepositoryName: my-repo
          BranchName: !Ref BranchName
        outputArtifacts:
          - name: SourceOutput
  - name: Build
    actions:
      - name: BuildAction
        actionTypeId:
          category: Build
          owner: AWS
          provider: CodeBuild
          version: '1'
        configuration:
          ProjectName: my-build-project
        inputArtifacts:
          - name: SourceOutput
        outputArtifacts:
          - name: BuildOutput
  - name: Deploy
    actions:
      - name: DeployAction
        actionTypeId:
          category: Deploy
          owner: AWS
          provider: ElasticBeanstalk
          version: '1'
        configuration:
          ApplicationName: my-eb-app
          EnvironmentName: my-eb-environment
        inputArtifacts:
          - name: BuildOutput
  - name: Test
    actions:
      - name: TestAction
        actionTypeId:
          category: Test
          owner: AWS
          provider: CodeBuild
          version: '1'
        configuration:
          ProjectName: my-test-project
        inputArtifacts:
          - name: BuildOutput
  - name: Approval
    actions:
      - name: ApprovalAction
        actionTypeId:
          category: Approval
          owner: AWS
          provider: Manual
          version: '1'
        inputArtifacts:
          - name: TestOutput
  - name: Publish
    actions:
      - name: PublishAction
        actionTypeId:
          category: Invoke
          owner: AWS
          provider: Lambda
          version: '1'
        configuration:
          FunctionName: my-publish-function
          UserParameters: !Sub '{"branchName": "${BranchName}"}'
        inputArtifacts:
          - name: TestOutput
